### ISSUE TITLE
problem with using tinystl

### ISSUE THREAD

**Issue by attilaz** [dtrebilco/Taren#1]
This iterator stuff looks useful, thanks.
I was trying to use it with tinystl ( https://github.com/bkaradzic/bx/tree/master/include/tinystl) and ran into an issue:

iterator.h:91:54: Member reference base type 'int *' is not a structure or union

I have replaced:
  using ValueRef = decltype(*std::declval<IterType>().operator*());
with 
  using ValueRef = decltype(*std::declval<IterType>());

And everything seems to work fine now.

**Comment by dtrebilco** [comment]
Thanks for the fix, it is now applied

**Comment by attilaz** [comment]
thanks
